name: ""
description: ""
inputs:
  generator:
    description: ""
    required: true
  spec:
    description: "the path"
    required: true
    default: "api.yaml"
  config:
    description: ""
    required: false
  repository:
    description: ""
    required: false
  repository_user:
    description: ""
    required: false
  repository_password:
    description: ""
    required: false
outputs:
  time:
    description: ""

runs:
  using: 'docker'
  image: 'Dockerfile'
